<a href="https://colab.research.google.com/github/vidhyasivasankari/AI-Powered-Workforce-Analytics-Talent-Intelligence-Dashboard/blob/main/SQL/SQL_Practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [93]:
import pandas as pd

data = {
    'Employee_ID': [101, 102, 103, 104, 105],
    'Name': ['Asha', 'Rahul', 'Priya', 'Kiran', 'Meena'],
    'Department': ['HR', 'IT', 'Finance', 'IT', 'HR'],
    'Salary': [40000, 55000, 50000, 65000, 45000],
    'Performance_Rating': [4, 5, 3, 4, 5]
}

In [94]:
df = pd.DataFrame(data)
display(df)

   Employee_ID   Name Department  Salary  Performance_Rating
0          101   Asha         HR   40000                   4
1          102  Rahul         IT   55000                   5
2          103  Priya    Finance   50000                   3
3          104  Kiran         IT   65000                   4
4          105  Meena         HR   45000                   5

In [95]:
display(df.head())

   Employee_ID   Name Department  Salary  Performance_Rating
0          101   Asha         HR   40000                   4
1          102  Rahul         IT   55000                   5
2          103  Priya    Finance   50000                   3
3          104  Kiran         IT   65000                   4
4          105  Meena         HR   45000                   5

In [96]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 5 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Employee_ID         5 non-null      int64
 1   Name                5 non-null      object
 2   Department          5 non-null      object
 3   Salary              5 non-null      int64
 4   Performance_Rating  5 non-null      int64
dtypes: int64(3), object(2)
memory usage: 332.0+ bytes

In [97]:
display(df.describe())

       Employee_ID        Salary  Performance_Rating
count     5.000000      5.000000             5.00000
mean    103.000000  51000.000000             4.20000
std       1.581139   9617.692031             0.83666
min     101.000000  40000.000000             3.00000
25%     102.000000  45000.000000             4.00000
50%     103.000000  50000.000000             4.00000
75%     104.000000  55000.000000             5.00000
max     105.000000  65000.000000             5.00000

In [98]:
df.isnull().sum()

Employee_ID           0
Name                  0
Department            0
Salary                0
Performance_Rating    0
dtype: int64

In [99]:
import pandas as pd

employee = {
    'Employee_ID': [101, 102, 103, 104, 105],
    'Name': ['Asha', 'Rahul', 'Priya', 'Kiran', 'Meena'],
    'Department': ['HR', 'IT', 'Finance', 'IT', 'HR'],
    'Salary': [40000, 55000, 50000, 65000, 45000]
}

df_emp = pd.DataFrame(employee)
display(df_emp)

   Employee_ID   Name Department  Salary
0          101   Asha         HR   40000
1          102  Rahul         IT   55000
2          103  Priya    Finance   50000
3          104  Kiran         IT   65000
4          105  Meena         HR   45000

In [100]:
department = {
    'Department': ['HR', 'IT', 'Finance', 'Marketing'],
    'Manager': ['Anita', 'Ramesh', 'Suresh', 'Deepa']
}

df_dept = pd.DataFrame(department)
display(df_dept)

  Department Manager
0         HR   Anita
1         IT  Ramesh
2    Finance  Suresh
3  Marketing   Deepa

In [101]:
inner_join = pd.merge(df_emp, df_dept, on='Department', how='inner')
display(inner_join)

   Employee_ID   Name Department  Salary Manager
0          101   Asha         HR   40000   Anita
1          102  Rahul         IT   55000  Ramesh
2          103  Priya    Finance   50000  Suresh
3          104  Kiran         IT   65000  Ramesh
4          105  Meena         HR   45000   Anita

In [102]:
left_join = pd.merge(df_emp, df_dept, on='Department', how='left')
display(left_join)

   Employee_ID   Name Department  Salary Manager
0          101   Asha         HR   40000   Anita
1          102  Rahul         IT   55000  Ramesh
2          103  Priya    Finance   50000  Suresh
3          104  Kiran         IT   65000  Ramesh
4          105  Meena         HR   45000   Anita

In [103]:
right_join = pd.merge(df_emp, df_dept, on='Department', how='right')
display(right_join)

   Employee_ID   Name Department   Salary Manager
0        101.0   Asha         HR  40000.0   Anita
1        105.0  Meena         HR  45000.0   Anita
2        102.0  Rahul         IT  55000.0  Ramesh
3        104.0  Kiran         IT  65000.0  Ramesh
4        103.0  Priya    Finance  50000.0  Suresh
5          NaN    NaN  Marketing      NaN   Deepa

In [104]:
outer_join = pd.merge(df_emp, df_dept, on='Department', how='outer')
display(outer_join)

   Employee_ID   Name Department   Salary Manager
0        103.0  Priya    Finance  50000.0  Suresh
1        101.0   Asha         HR  40000.0   Anita
2        105.0  Meena         HR  45000.0   Anita
3        102.0  Rahul         IT  55000.0  Ramesh
4        104.0  Kiran         IT  65000.0  Ramesh
5          NaN    NaN  Marketing      NaN   Deepa

In [105]:
df_emp.head()

   Employee_ID   Name Department  Salary
0          101   Asha         HR   40000
1          102  Rahul         IT   55000
2          103  Priya    Finance   50000
3          104  Kiran         IT   65000
4          105  Meena         HR   45000

In [106]:
df_emp.tail()

   Employee_ID   Name Department  Salary
0          101   Asha         HR   40000
1          102  Rahul         IT   55000
2          103  Priya    Finance   50000
3          104  Kiran         IT   65000
4          105  Meena         HR   45000

In [107]:
df_emp.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Employee_ID  5 non-null      int64
 1   Name         5 non-null      object
 2   Department   5 non-null      object
 3   Salary       5 non-null      int64
dtypes: int64(2), object(2)
memory usage: 292.0+ bytes

In [108]:
df_emp.describe()

       Employee_ID        Salary
count     5.000000      5.000000
mean    103.000000  51000.000000
std       1.581139   9617.692031
min     101.000000  40000.000000
25%     102.000000  45000.000000
50%     103.000000  50000.000000
75%     104.000000  55000.000000
max     105.000000  65000.000000

In [109]:
df_emp.isnull().sum()

Employee_ID    0
Name           0
Department     0
Salary         0
dtype: int64

In [110]:
df_emp['Salary'].max()

65000

In [111]:
df_emp['Salary'].min()

40000

In [112]:
df_emp['Salary'].mean()

np.float64(51000.0)

In [113]:
df_emp.sort_values(by='Salary', ascending=False)

   Employee_ID   Name Department  Salary
3          104  Kiran         IT   65000
1          102  Rahul         IT   55000
2          103  Priya    Finance   50000
4          105  Meena         HR   45000
0          101   Asha         HR   40000

In [114]:
df_emp[df_emp['Salary'] > 50000]

   Employee_ID   Name Department  Salary
1          102  Rahul         IT   55000
3          104  Kiran         IT   65000

In [115]:
df_emp.groupby('Department')['Salary'].mean()

Department
Finance    50000.0
HR         42500.0
IT         60000.0
Name: Salary, dtype: float64

In [116]:
df_emp['Bonus'] = df_emp['Salary'] * 0.10
display(df_emp)

   Employee_ID   Name Department  Salary   Bonus
0          101   Asha         HR   40000  4000.0
1          102  Rahul         IT   55000  5500.0
2          103  Priya    Finance   50000  5000.0
3          104  Kiran         IT   65000  6500.0
4          105  Meena         HR   45000  4500.0

In [117]:
df_emp.rename(columns={'Salary': 'Monthly_Salary'})

   Employee_ID   Name Department  Monthly_Salary   Bonus
0          101   Asha         HR           40000  4000.0
1          102  Rahul         IT           55000  5500.0
2          103  Priya    Finance           50000  5000.0
3          104  Kiran         IT           65000  6500.0
4          105  Meena         HR           45000  4500.0

In [118]:
df_emp.drop('Bonus', axis=1)

   Employee_ID   Name Department  Salary
0          101   Asha         HR   40000
1          102  Rahul         IT   55000
2          103  Priya    Finance   50000
3          104  Kiran         IT   65000
4          105  Meena         HR   45000

In [119]:
import sqlite3

conn = sqlite3.connect("employee.db")
cursor = conn.cursor()

print("Database Connected Successfully")

Database Connected Successfully

In [133]:
cursor.execute("SELECT * FROM Project")
print(cursor.fetchall())

[(201, 'AI Dashboard', 2, 500000), (202, 'HR Portal', 1, 200000), (203, 'Finance System', 3, 350000), (204, 'Recruitment App', 1, 250000)]

In [134]:
cursor.execute("SELECT * FROM Employee")
print(cursor.fetchall())

[(101, 'Asha', 'HR', 40000, 23), (102, 'Rahul', 'IT', 55000, 25), (103, 'Priya', 'Finance', 50000, 24), (104, 'Kiran', 'IT', 65000, 27), (105, 'Meena', 'HR', 45000, 22)]

In [121]:
cursor.execute("SELECT Name, Salary FROM Employee")
print(cursor.fetchall())

[('Asha', 40000), ('Rahul', 55000), ('Priya', 50000), ('Kiran', 65000), ('Meena', 45000)]

In [136]:
cursor.execute("""
SELECT * FROM Employee
WHERE Salary > 50000
""")
print(cursor.fetchall())

[(102, 'Rahul', 'IT', 55000, 25), (104, 'Kiran', 'IT', 65000, 27)]

In [137]:
cursor.execute("""
SELECT * FROM Employee
WHERE Department = 'IT'
AND Salary > 50000
""")

print(cursor.fetchall())

[(102, 'Rahul', 'IT', 55000, 25), (104, 'Kiran', 'IT', 65000, 27)]

In [138]:
cursor.execute("""
SELECT *
FROM Employee
WHERE Department = 'HR'
OR Salary > 60000
""")

print(cursor.fetchall())

[(101, 'Asha', 'HR', 40000, 23), (104, 'Kiran', 'IT', 65000, 27), (105, 'Meena', 'HR', 45000, 22)]

In [139]:
cursor.execute("""
SELECT *
FROM Employee
ORDER BY Salary ASC
""")

print(cursor.fetchall())

[(101, 'Asha', 'HR', 40000, 23), (105, 'Meena', 'HR', 45000, 22), (103, 'Priya', 'Finance', 50000, 24), (102, 'Rahul', 'IT', 55000, 25), (104, 'Kiran', 'IT', 65000, 27)]

In [126]:
cursor.execute("""
SELECT *
FROM Employee
ORDER BY Salary DESC
""")

print(cursor.fetchall())

[(104, 'Kiran', 'IT', 65000, 27), (102, 'Rahul', 'IT', 55000, 25), (103, 'Priya', 'Finance', 50000, 24), (105, 'Meena', 'HR', 45000, 22), (101, 'Asha', 'HR', 40000, 23)]

In [140]:
cursor.execute("""
SELECT COUNT(*)
FROM Employee
""")

print(cursor.fetchall())

[(5,)]

In [141]:
cursor.execute("""
SELECT SUM(Salary)
FROM Employee
""")

print(cursor.fetchall())

[(255000,)]

In [142]:
cursor.execute("""
SELECT AVG(Salary)
FROM Employee
""")

print(cursor.fetchall())

[(51000.0,)]

In [143]:
cursor.execute("""
SELECT MAX(Salary)
FROM Employee
""")

print(cursor.fetchall())

[(65000,)]

In [144]:
cursor.execute("""
SELECT MIN(Salary)
FROM Employee
""")

print(cursor.fetchall())

[(40000,)]

In [145]:
cursor.execute("""
SELECT Department,
COUNT(*) AS Total_Employees
FROM Employee
GROUP BY Department
""")

print(cursor.fetchall())

[('Finance', 1), ('HR', 2), ('IT', 2)]

In [146]:
cursor.execute("""
SELECT Department,
AVG(Salary) AS Average_Salary
FROM Employee
GROUP BY Department
""")

print(cursor.fetchall())

[('Finance', 50000.0), ('HR', 42500.0), ('IT', 60000.0)]

In [147]:
cursor.execute("""
SELECT Department,
COUNT(*) AS Total_Employees
FROM Employee
GROUP BY Department
HAVING COUNT(*) > 1
""")

print(cursor.fetchall())

[('HR', 2), ('IT', 2)]

In [148]:
cursor.execute("""
SELECT DISTINCT Department
FROM Employee
""")

print(cursor.fetchall())

[('HR',), ('IT',), ('Finance',)]

In [149]:
cursor.execute("""
SELECT *
FROM Employee
WHERE Name LIKE 'A%'
""")

print(cursor.fetchall())

[(101, 'Asha', 'HR', 40000, 23)]

In [150]:
cursor.execute("""
SELECT *
FROM Employee
WHERE Salary BETWEEN 40000 AND 55000
""")

print(cursor.fetchall())

[(101, 'Asha', 'HR', 40000, 23), (102, 'Rahul', 'IT', 55000, 25), (103, 'Priya', 'Finance', 50000, 24), (105, 'Meena', 'HR', 45000, 22)]

In [151]:
cursor.execute("""
SELECT *
FROM Employee
WHERE Department IN ('HR','IT')
""")

print(cursor.fetchall())

[(101, 'Asha', 'HR', 40000, 23), (102, 'Rahul', 'IT', 55000, 25), (104, 'Kiran', 'IT', 65000, 27), (105, 'Meena', 'HR', 45000, 22)]

In [152]:
cursor.execute("""
SELECT *
FROM Employee
LIMIT 3
""")

print(cursor.fetchall())

[(101, 'Asha', 'HR', 40000, 23), (102, 'Rahul', 'IT', 55000, 25), (103, 'Priya', 'Finance', 50000, 24)]

In [153]:
cursor.execute("""
UPDATE Employee
SET Salary = 70000
WHERE Name = 'Asha'
""")

conn.commit()

cursor.execute("SELECT * FROM Employee")
print(cursor.fetchall())

[(101, 'Asha', 'HR', 70000, 23), (102, 'Rahul', 'IT', 55000, 25), (103, 'Priya', 'Finance', 50000, 24), (104, 'Kiran', 'IT', 65000, 27), (105, 'Meena', 'HR', 45000, 22)]

In [154]:
cursor.execute("""
DELETE FROM Employee
WHERE Name = 'Meena'
""")

conn.commit()

cursor.execute("SELECT * FROM Employee")
print(cursor.fetchall())

[(101, 'Asha', 'HR', 70000, 23), (102, 'Rahul', 'IT', 55000, 25), (103, 'Priya', 'Finance', 50000, 24), (104, 'Kiran', 'IT', 65000, 27)]